cp ~/.bashrc  ~/.bashrc.bkp
exec 6>&1
exec 1>~/.bashrc
echo #autodeployed by lucabodd
echo # Automatically generated by ossim-reconfig scripts. DO NOT TOUCH!
echo # ~/.bashrc: executed by bash(1) for non-login shells.
echo
echo #File changed: condition from != to ==
echo if [ "$jailbreak" == "yes" ];then
echo if [[ $- =~ "i" ]];then
echo         ossim-setup
echo exit
echo fi
echo fi
echo export PS1='\h:\w\$ '
echo umask 022
echo export LS_OPTIONS='--color=auto'
echo eval "`dircolors`"
echo alias ls='ls $LS_OPTIONS'
echo alias ll='ls $LS_OPTIONS -l'
echo alias l='ls $LS_OPTIONS -lA'
echo alias du='du -kh'
echo alias df='df -kTh'
echo alias grep='grep --color=auto'
echo alias egrep='egrep --color=auto'
echo alias fgrep='fgrep --color=auto'
echo alias rgrep='rgrep --color=auto'
echo export LC_ALL='C'
echo export HISTTIMEFORMAT='%F %T '
exec 1>&-
exec 1>&6
exec 6>&-

exec 6>&1
exec 1>/usr/local/bin/cluster-delete-agent
echo if [ "$#" -ne 1 ]; then
echo 	echo "Illegal number of parameters"
echo 	echo "You need to provide onli cluster name or hostname as parameter"
echo fi
echo for i in $(/var/ossec/bin/manage_agents -l | grep $1 | awk '{ print $2 }' | tr -d ','); do
echo 	/var/ossec/bin/manage_agents -r $i;
echo done
echo /var/ossec/bin/ossec-control restart;
exec 1>&-
exec 1>&6
exec 6>&-

chmod a+x /usr/local/bin/cluster-delete-agent
